// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Curso struct {
	CourseID       int     `json:"courseID"`
	InstructorName string  `json:"instructorName"`
	Title          string  `json:"title"`
	Description    string  `json:"description"`
	Price          float64 `json:"price"`
	Category       string  `json:"category"`
	ImageURL       string  `json:"imageURL"`
}

type Mutation struct {
}

type Query struct {
}
